export const LIST = [
  {
    id: 11,
    name: "YEEZY BOOST",
    title: "YEEZY BOOST 700 MNVN ADULTS",
    sex: "Male",
    price: "6.000.000",
  },
  {
    id: 12,
    name: "ADILETTE",
    title: "Adilette 2.0 Pride Sandals",
    sex: "Male",
    price: "12.000.000",
  },
  {
    id: 13,
    name: "NIZZA",
    title: "Nizza Pride Shoes",
    sex: "Male",
    price: "3.000.000",
  },
  {
    id: 14,
    name: "NMDR1",
    title: "Shoes NMD_R1 Marimekko",
    sex: "Female",
    price: "9.000.000",
  },
  {
    id: 15,
    name: "NIZZASLIP",
    title: "Nizza Pride Slip-On Shoes",
    sex: "Female",
    price: "21.000.000",
  },
  {
    id: 16,
    name: "DORUMLOW",
    title: "Forum Pride Low Neck Shoes",
    sex: "Male",
    price: "12.000.000",
  },
  {
    id: 17,
    name: "ZX2K",
    title: "ZX 2K Boost 2.0 Shoes",
    sex: "Male",
    price: "3.000.000",
  },
  {
    id: 18,
    name: "SUPERSTAR",
    title: "Superstar Shoes",
    sex: "Male",
    price: "7.000.000",
  },
  {
    id: 19,
    name: "FORUM",
    title: "Forum shoes",
    sex: "Male",
    price: "14.000.000",
  },
];
